# Generated by Django 4.2.4 on 2023-10-10 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activitePrincipale', models.CharField(max_length=300)),
                ('responsable_execution', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Antenne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BulletinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('resultatAtteints', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('lieuxExecution', models.CharField(default=None, max_length=150)),
                ('statut', models.CharField(default=None, max_length=100)),
                ('justification', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('mesuresCorrectives', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('leconAprise', models.CharField(blank=True, default=None, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coordination_Nationale_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordination_national', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30, unique=True)),
                ('antenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.antenne')),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('code_project', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('finance_par', models.CharField(max_length=50)),
                ('date_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_fin', models.DateField(default=django.utils.timezone.now)),
                ('duree', models.CharField(default=0, max_length=50)),
                ('plan_action', models.CharField(max_length=100)),
                ('programme_solicite', models.CharField(max_length=100)),
                ('contextActualiseProgramme', models.TextField()),
                ('descImpactAttenduProg', models.TextField()),
                ('statut', models.CharField(default='En attente de soumission', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(default=None, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DomaineProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif_lac_de_dvpt_dans_ce_domaine', models.CharField(default=None, max_length=500)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='APP_LAC.domaine')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet')),
            ],
        ),
        migrations.CreateModel(
            name='EchoBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default=None, max_length=250)),
                ('description', models.TextField(default=None)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Fonctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=30, unique=True)),
                ('departement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.departement')),
            ],
        ),
        migrations.CreateModel(
            name='NoteService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default=None, max_length=250)),
                ('message', models.TextField(default=None)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartenaireProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partenaire', models.CharField(default=None, max_length=100)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Pays_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=50)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Province_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.pays_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Volet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volet', models.CharField(default=None, max_length=350)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.domaine')),
            ],
        ),
        migrations.CreateModel(
            name='VoletProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif_LAC', models.CharField(max_length=200)),
                ('objectif_SMART', models.CharField(max_length=200)),
                ('vue_d_ensemble', models.CharField(max_length=200)),
                ('description_des_effets', models.CharField(max_length=200)),
                ('nbre_succes', models.IntegerField(default=0)),
                ('enumererpersonnel', models.TextField(default=None)),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.domaineprojet')),
                ('volet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.volet')),
            ],
        ),
        migrations.CreateModel(
            name='Ville_Territoire_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville_territoire', models.CharField(max_length=100)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.province_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=50)),
                ('postnom', models.CharField(default=None, max_length=50)),
                ('prenom', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('nom_utilisateur', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=50)),
                ('typeCompte', models.IntegerField(default=1)),
                ('email', models.EmailField(default=None, max_length=50)),
                ('tel1', models.CharField(default=None, max_length=13)),
                ('tel2', models.CharField(blank=True, max_length=13, null=True)),
                ('agentFolderPht', models.CharField(blank=True, max_length=100, null=True)),
                ('agentFolderDoc', models.CharField(blank=True, max_length=100, null=True)),
                ('photo', models.FileField(blank=True, default=None, null=True, upload_to='photos')),
                ('cv', models.FileField(blank=True, default=None, null=True, upload_to='CV')),
                ('lettre', models.FileField(blank=True, default=None, null=True, upload_to='lettre')),
                ('contrat', models.FileField(blank=True, default=None, null=True, upload_to='contrat')),
                ('carteid', models.FileField(blank=True, default=None, null=True, upload_to='carte')),
                ('diplome1', models.FileField(blank=True, default=None, null=True, upload_to='dip1')),
                ('diplome2', models.FileField(blank=True, default=None, null=True, upload_to='dip2')),
                ('diplome3', models.FileField(blank=True, default=None, null=True, upload_to='dip2')),
                ('antenne', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.antenne')),
                ('departement', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.departement')),
                ('fonction', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='APP_LAC.fonctions')),
            ],
        ),
        migrations.CreateModel(
            name='SuiviContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dureeContrat', models.CharField(default=None, max_length=100)),
                ('cahierDeCharge', models.TextField(blank=True, default=None, null=True)),
                ('salaire', models.CharField(default=None, max_length=100)),
                ('formationbourses', models.TextField(blank=True, default=None, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Suivi_de_indicateurs_projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicateur_lac', models.CharField(default=None, max_length=300, null=True)),
                ('base_line_gab', models.CharField(default=None, max_length=300, null=True)),
                ('cible_NA', models.CharField(default=None, max_length=300, null=True)),
                ('source_outils', models.CharField(default=None, max_length=300, null=True)),
                ('frequence_de_collecte', models.CharField(default=None, max_length=300, null=True)),
                ('periode_execution', models.JSONField(null=True)),
                ('activite_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.activiteprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_activite_Ap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sousactivite', models.TextField()),
                ('descapproche', models.TextField()),
                ('besoinenappui', models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default=None, max_length=10)),
                ('outildesupervision', models.CharField(max_length=100)),
                ('lieu_execution', models.CharField(max_length=100)),
                ('date_debut', models.DateField(default=None)),
                ('date_fin', models.DateField(default=None)),
                ('date_rapportage', models.DateField(default=None)),
                ('ligne_budgetaire_correspondante', models.CharField(max_length=100)),
                ('indicateur', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.suivi_de_indicateurs_projet')),
                ('partenairetatique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='APP_LAC.partenaireprojet')),
                ('partenairetechnique', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partech', to='APP_LAC.partenaireprojet')),
            ],
        ),
        migrations.CreateModel(
            name='Planification_Detaille_Execution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outilDecollecte', models.CharField(max_length=200)),
                ('methodeDecollecte', models.CharField(max_length=200)),
                ('frequenceDecollecte', models.CharField(max_length=200)),
                ('activiteprincipal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.activiteprincipal')),
                ('indicateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.suivi_de_indicateurs_projet')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRealisation_Sitrep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoRealisation', models.ImageField(upload_to='sitrep')),
                ('bulletin_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.bulletininfo')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel_de_mise_en_oeuvre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.CharField(default=None, max_length=300)),
                ('effectif', models.IntegerField()),
                ('nombre_jour', models.IntegerField()),
                ('sexe_souhaite', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default=None, max_length=10)),
                ('role_responsabilite', models.CharField(default=None, max_length=300)),
                ('profil_poste', models.CharField(default=None, max_length=200)),
                ('volet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.voletprojet')),
            ],
        ),
        migrations.CreateModel(
            name='Gestion_des_risques_SI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('mesure', models.CharField(max_length=300)),
                ('responsable', models.CharField(max_length=300)),
                ('volet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.voletprojet')),
            ],
        ),
        migrations.CreateModel(
            name='EtatdeBesoin_LigneBudgetaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat_de_besoin', models.CharField(max_length=100)),
                ('ligne_budgetaire', models.CharField(default=0, max_length=100)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Coordination_Provinciale_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordination_provinciale', models.CharField(max_length=100)),
                ('cordination_nationale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.coordination_nationale_projet')),
            ],
        ),
        migrations.AddField(
            model_name='coordination_nationale_projet',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet'),
        ),
        migrations.AddField(
            model_name='bulletininfo',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet'),
        ),
        migrations.CreateModel(
            name='BudgetEtPlanDecaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLigne', models.IntegerField(default=1)),
                ('designation', models.CharField(default=None, max_length=100)),
                ('specification', models.CharField(default=None, max_length=400)),
                ('unite', models.CharField(default=None, max_length=100, null=True)),
                ('quantite', models.FloatField(default=1, max_length=10)),
                ('frequence', models.IntegerField(default=1, null=True)),
                ('prixUnit', models.FloatField(default=1, max_length=100)),
                ('prixTot', models.FloatField(default=1, max_length=100)),
                ('partenaire_1', models.FloatField(default=0, null=True)),
                ('partenaire_2', models.FloatField(default=0, null=True)),
                ('lac_asbl', models.FloatField(default=0, null=True)),
                ('observation', models.CharField(max_length=300, null=True)),
                ('activite_principale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.activiteprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='Axe_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axe', models.CharField(max_length=100)),
                ('nombre_beneficiares', models.IntegerField(default=1)),
                ('ville_territoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.ville_territoire_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Antenne_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antenne_projet', models.CharField(max_length=100)),
                ('coordination_provinciale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.coordination_provinciale_projet')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('activitePrevue', models.TextField(default=None)),
                ('lieu', models.CharField(default=None, max_length=250)),
                ('heure', models.CharField(default=None, max_length=10)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.utilisateur')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='activiteprincipal',
            name='volet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.voletprojet'),
        ),
    ]
