# Generated by Django 4.2.4 on 2023-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sous_activite_ap',
            name='contribution',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sous_activite_ap',
            name='inclusion_pers_besoin',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='sous_activite_ap',
            name='strategie_genre',
            field=models.TextField(default=None),
        ),
    ]
