# Generated by Django 4.2.4 on 2023-10-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0002_sous_activite_ap_contribution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sous_activite_ap',
            name='partenairetatique',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='sous_activite_ap',
            name='partenairetechnique',
            field=models.JSONField(default=None),
        ),
    ]
