# Generated by Django 4.2.4 on 2023-10-10 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0003_alter_sous_activite_ap_partenairetatique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sous_activite_ap',
            name='partenairetatique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='APP_LAC.partenaireprojet'),
        ),
        migrations.AlterField(
            model_name='sous_activite_ap',
            name='partenairetechnique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='partech', to='APP_LAC.partenaireprojet'),
        ),
    ]
