# Generated by Django 4.2.4 on 2023-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0004_alter_sous_activite_ap_partenairetatique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetetplandecaissement',
            name='lac_asbl',
        ),
        migrations.RemoveField(
            model_name='budgetetplandecaissement',
            name='partenaire_1',
        ),
        migrations.RemoveField(
            model_name='budgetetplandecaissement',
            name='partenaire_2',
        ),
        migrations.AddField(
            model_name='budgetetplandecaissement',
            name='partenaire',
            field=models.JSONField(default=0),
        ),
    ]
