# Generated by Django 4.2.4 on 2023-10-12 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0005_remove_budgetetplandecaissement_lac_asbl_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mapping_Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.CharField(max_length=50)),
                ('grade_agent', models.CharField(max_length=50)),
                ('effectif_recherche', models.IntegerField(default=1)),
                ('affectation', models.CharField(max_length=50)),
                ('nombre_de_jours', models.IntegerField(default=0)),
                ('reponsables_h', models.CharField(max_length=50)),
                ('personnel_supervise', models.CharField(max_length=50)),
                ('responsable_cle', models.CharField(max_length=50)),
                ('description_taches', models.CharField(max_length=50)),
                ('profil_de_ce_poste', models.CharField(max_length=50)),
                ('type_de_recrutement', models.CharField(max_length=50)),
                ('debut_recrutement', models.DateField(default=datetime.datetime(2023, 10, 12, 11, 18, 41, 395862))),
                ('fin_recrutement', models.DateField(default=datetime.datetime(2023, 10, 12, 11, 18, 41, 395862))),
                ('type_contrat', models.CharField(max_length=50)),
                ('nature_contrat', models.CharField(max_length=50)),
                ('id_agent', models.CharField(max_length=50)),
                ('date_debut_contrat', models.CharField(max_length=50)),
                ('date_debut_fin', models.CharField(max_length=50)),
                ('date_premiere_evaluation', models.CharField(max_length=50)),
                ('total_salaire', models.FloatField(default=0.0)),
                ('ligne_budgetaire', models.CharField(max_length=50)),
                ('impot_DGI', models.FloatField(default=0.0)),
                ('retune_CNSS', models.FloatField(default=0.0)),
                ('retune_NPP', models.FloatField(default=0.0)),
                ('retune_CaisseSociale', models.FloatField(default=0.0)),
                ('net_a_payer', models.FloatField(default=0.0)),
                ('equipement', models.CharField(default='...', max_length=500)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP_LAC.doc_projet')),
            ],
        ),
    ]
