# Generated by Django 4.2.4 on 2023-10-12 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0006_mapping_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping_projet',
            name='debut_recrutement',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 13, 57, 5, 609667)),
        ),
        migrations.AlterField(
            model_name='mapping_projet',
            name='fin_recrutement',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 13, 57, 5, 609667)),
        ),
        migrations.AlterField(
            model_name='sous_activite_ap',
            name='partenairetatique',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sous_activite_ap',
            name='partenairetechnique',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Planification_Detaille_Execution',
        ),
    ]
