# Generated by Django 4.2.4 on 2023-10-12 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0009_remove_sous_activite_ap_ligne_budgetaire_correspondante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping_projet',
            name='debut_recrutement',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 23, 21, 13, 310671)),
        ),
        migrations.AlterField(
            model_name='mapping_projet',
            name='fin_recrutement',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 23, 21, 13, 310671)),
        ),
    ]
