# Generated by Django 4.2.4 on 2023-10-12 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0010_alter_mapping_projet_debut_recrutement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapping_projet',
            name='debut_recrutement',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 23, 22, 15, 219824)),
        ),
        migrations.AlterField(
            model_name='mapping_projet',
            name='fin_recrutement',
            field=models.DateField(default=datetime.datetime(2023, 10, 12, 23, 22, 15, 219824)),
        ),
    ]
