# Generated by Django 4.2.4 on 2023-10-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0012_alter_mapping_projet_debut_recrutement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetetplandecaissement',
            name='partenaire',
            field=models.JSONField(default=dict),
        ),
    ]
