# Generated by Django 4.2.4 on 2023-10-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0015_remove_mapping_projet_date_debut_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voletprojet',
            name='description_des_effets',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='voletprojet',
            name='nbre_succes',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='voletprojet',
            name='objectif_LAC',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='voletprojet',
            name='objectif_SMART',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='voletprojet',
            name='vue_d_ensemble',
            field=models.TextField(default=None),
        ),
    ]
