# Generated by Django 4.2.4 on 2023-10-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0016_alter_voletprojet_description_des_effets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voletprojet',
            name='nbre_succes',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
