# Generated by Django 4.2.4 on 2023-10-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0018_alter_activiteprincipal_activiteprincipale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestion_des_risques_si',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='gestion_des_risques_si',
            name='mesure',
            field=models.TextField(default=None),
        ),
    ]
