# Generated by Django 4.2.4 on 2023-10-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_LAC', '0019_alter_gestion_des_risques_si_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc_projet',
            name='etat',
            field=models.CharField(default='En cours', max_length=100),
        ),
    ]
